version: "3.1"

services:
  gateway:
    build: ./nginx-gateway
    ports:
      - "8080:80"

  auth0-sample:
    image: auth0-sample:local

  oidc-bridge:
    image: tru.id/oidc-bridge:local
    env_file:
      - .env.prod
