version: "3.1"

services:
  gateway:
    build: ./nginx-gateway
    ports:
      - "8080:80"

  sample-ui:
    image: tru.id/sample-ui:local
    env_file:
      - ${OIDC_CONFIG_FILE}
    # uncomment if you are running gluu example and need to load a trust store
    volumes:
      - ./integration-gluu/:/opt/truid

  oidc-bridge:
    image: tru.id/oidc-bridge:local
    env_file:
      - ${OIDC_CONFIG_FILE}
    # uncomment if you are running gluu example and need to load a trust store
    volumes:
      - ./integration-gluu/:/opt/truid
