version: "3.1"

services:
  gateway:
    build: ./nginx-gateway
    ports:
      - "8080:80"

  sample-ui:
    image: tru.id/sample-ui:local
    env_file:
      - ${OIDC_CONFIG_FILE}
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256

  oidc-bridge:
    image: tru.id/oidc-bridge:local
    env_file:
      - ${OIDC_CONFIG_FILE}
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256
